# Probability in a world teeming with data: a neo-Baroque perspective on contemporary belief-structures

## Abstract
Since its Baroque invention [@hacking_emergence_1975], probability has been a double-sided coin. On one side, it concerns degrees of belief (the so-called 'subjective' view), and on the other side, frequencies, or how often things happen in the world (the so-called 'objective' view). In the last few centuries, one side of this coin has come up more often -- the frequencies version of probability. Yet, as many historians of statistics, and statisticians themselve recognise, probability as degree of belief has never disappeared. It has only occurred less often, and been less often the object of belief. Indeed, this ineluctable entwining of belief and events, of subjective-objective, seems quintessentially Baroque in its interweaving and folding together of inside and outside. Drawing on both histories of statistics, and Gilles Deleuze's understanding of monads as 'simple, inverse, distribution numbers' [@deleuze_fold_1993], this paper examines the resurgence of the probability as degree of belief in the face of a world seemingly teeming with data. It argues that in the last few decades of statistical practice associated especially with 'Bayesian inference' and the techniques of Markov Chain Monte Carlo (MCMC) simulation, we see a re-configured and super-imposed concept of probability taking shape. As these practices pervade diverse scientific fields, commerce, government and industry, we might be seeing a different epistemic materialisation taking shape in which beliefs and events are less separate. On the contrary, through computation, subjective belief is exteriorised in simulated events, and a certain staging of events are reshaped as updateable beliefs. 

## Introduction

In the US Presidential elections of November 2012, the data analysis team supporting the re-election of Barack Obama were said to be running a statistical model of the election 66,000 times every night [@scherer_how_2012]. This model, delying on much polling data, records of past voting behaviour, and many other demographic features, was guiding tactical decisions about everything from where the presidential candidate would speak to the telephone calls that targeted specific groups of swing voters. In the media reports, the statistical model was favourably compared to the almost equally well-funded data analysis used by the Republican candidate, Mitch Romney.  The outstanding feature of this information, widely reported in television news and internationally in print media (_Time_, _New York Times_, _The Observer_) it seems to me is the figure of 66,000 runs of the model every night. Why so many thousand runs? This question was not addressed in the media reports, nor surprisingly, addressed in the online discussion on blogs and other online forums that followed. This paper seeks to provide an answer to  question of the power of repetition associated with data and models today. I only present this example as one amongst many recent illustrations of the power attributed to data. The answer is to be found, I suggest, in probability. Hardly ever discussed in media accounts of the growth of big data,  certain shifts in the role played by probability changing the meaning and value of data as such, and hence, everything that depends on data. 

In exploring recent mutations in probability, a Baroque perspective is not only useful but perhaps essential.  Summarising his own account of the emergence of probability, the philosopher and historian Ian Hacking writes:

>I claimed in _The Emergence of Probability_ that our idea of probability is a  Janus-faced mid-seventheenth-century mutation in the Renaissance idea of signs. It came into being with a frequency aspect and a degree-of-belief aspect [@hacking_taming_1990, 96].

Indeed, in the work from 1975, Hacking, writing largely prior to the shifts in probability practice I discuss, claims that there was no probability prior to 1660 [@hacking_emergence_1975]. Not only is probability a Baroque invention, the fundamental instability that permits ongoing mutations in the concept has a distinctively Baroque flavour in the way that it combines something happening in the world with something that pertains to subjects. There is nothing controversial in this claim. Historian of statistics and statisticians themselves regularly speak about probability in the same way. Although the history of statistics shows various distributions and permutations of emphasis on the subjective and objective versions of probability, the parlance is now relatively normalised around a divided view of probability. 

